// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCizYemqk5c3Sl9cP2z6AVwmlMQPOL7v7w',
    appId: '1:1094189532218:web:03daf8df80759edc816103',
    messagingSenderId: '1094189532218',
    projectId: 'chat-now-45786',
    authDomain: 'chat-now-45786.firebaseapp.com',
    storageBucket: 'chat-now-45786.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0HLVIWZwotP1FSGvbDWcw_4E4fuvciBI',
    appId: '1:1094189532218:android:63300e740dfc286b816103',
    messagingSenderId: '1094189532218',
    projectId: 'chat-now-45786',
    storageBucket: 'chat-now-45786.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOwniviwt0JyZ9E3UBfWNhhZMe366ue4o',
    appId: '1:1094189532218:ios:af18ec284e0480fd816103',
    messagingSenderId: '1094189532218',
    projectId: 'chat-now-45786',
    storageBucket: 'chat-now-45786.firebasestorage.app',
    iosBundleId: 'com.example.chatnow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOwniviwt0JyZ9E3UBfWNhhZMe366ue4o',
    appId: '1:1094189532218:ios:af18ec284e0480fd816103',
    messagingSenderId: '1094189532218',
    projectId: 'chat-now-45786',
    storageBucket: 'chat-now-45786.firebasestorage.app',
    iosBundleId: 'com.example.chatnow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCizYemqk5c3Sl9cP2z6AVwmlMQPOL7v7w',
    appId: '1:1094189532218:web:af944d3440d18ce8816103',
    messagingSenderId: '1094189532218',
    projectId: 'chat-now-45786',
    authDomain: 'chat-now-45786.firebaseapp.com',
    storageBucket: 'chat-now-45786.firebasestorage.app',
  );
}
